// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC51-a9hIwNjjbe0pODm0nINUdScgIoArQ',
    appId: '1:354669315412:web:1712965f3c46a26be474c1',
    messagingSenderId: '354669315412',
    projectId: 'sabai-job',
    authDomain: 'sabai-job.firebaseapp.com',
    storageBucket: 'sabai-job.firebasestorage.app',
    measurementId: 'G-MG3Y6KS3K8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcdAMuVioh2HlUDGgVgqtKQt9LCVbEQ9Q',
    appId: '1:354669315412:android:a3d98d9d744fd439e474c1',
    messagingSenderId: '354669315412',
    projectId: 'sabai-job',
    storageBucket: 'sabai-job.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDt4pJ7EjKiJasZdPmx4Y-N8a26CtR7_4E',
    appId: '1:354669315412:ios:ceed8b79201b056de474c1',
    messagingSenderId: '354669315412',
    projectId: 'sabai-job',
    storageBucket: 'sabai-job.firebasestorage.app',
    iosBundleId: 'com.sabaijob.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDt4pJ7EjKiJasZdPmx4Y-N8a26CtR7_4E',
    appId: '1:354669315412:ios:4e297da30abc4aede474c1',
    messagingSenderId: '354669315412',
    projectId: 'sabai-job',
    storageBucket: 'sabai-job.firebasestorage.app',
    iosBundleId: 'com.example.sabaiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC51-a9hIwNjjbe0pODm0nINUdScgIoArQ',
    appId: '1:354669315412:web:ada4abde0aef1994e474c1',
    messagingSenderId: '354669315412',
    projectId: 'sabai-job',
    authDomain: 'sabai-job.firebaseapp.com',
    storageBucket: 'sabai-job.firebasestorage.app',
    measurementId: 'G-1YFB1RMCW1',
  );
}
